# Generated by Django 5.0.7 on 2024-12-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0002_remove_appointment_date_time_appointment_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_vip",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="vin",
            field=models.CharField(max_length=17),

        ),
    ]
