# Generated by Django 5.0.7 on 2024-12-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0005_alter_automobilevo_vin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="is_vip",
        ),
        migrations.AlterField(
            model_name="automobilevo",
            name="vin",
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
