# Generated by Django 5.0.7 on 2024-12-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0006_remove_appointment_is_vip_alter_automobilevo_vin"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="vip_status",
            field=models.BooleanField(default=False),
        ),
    ]
